services:
  jobSearchWebUI:
    container_name: jobSearchWebUI
    image: ghcr.io/even44/TODO
    ports: "4200:4200"
    restart: unless-stopped
    depends_on:
      - jobSearchAPI
  jobSearchAPI:
    container_name: JobSearchAPI
    image: ghcr.io/even44/jobsearchapi:dev
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - db
  db:
    container_name: MariaDB
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - "./data:/var/lib/mysql:Z"
    environment:
      MARIADB_ROOT_PASSWORD: superroot
      MARIADB_DATABASE: jobsearchdb


    