services:
  jobSearchAPI:
    container_name: JobSearchAPI
    image: ghcr.io/even44/jobsearchapi:dev
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - db
    environment:
      API_PORT: 3001
      TRUSTED_ORIGIN: http://172.30.20.200:4200
      DB_USER: root
      DB_PASSWORD: superroot
      DB_URL: db
      DB_PORT: 3306
      SECURE_COOKIES: false

  db:
    container_name: MariaDB
    image: mariadb
    restart: always
    ports:
      - "3306"
    volumes:
      - "./data:/var/lib/mysql:Z"
    environment:
      MARIADB_ROOT_PASSWORD: superroot
      MARIADB_DATABASE: jobsearchdb