services:
  jobSearchAPI:
    container_name: JobSearchAPI
    image: ghcr.io/even44/jobsearchapi:dev
    ports:
      - "3001:3001"
    restart: unless-stopped
	
    depends_on:
      - db
  db:
    container_name: MariaDB
    image: mariadb
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - "./data:/var/lib/mysql:Z"
    environment:
      MARIADB_ROOT_PASSWORD: superroot


    